const fs = require('fs');

let content = fs.readFileSync('src/app/properties/[id]/page.tsx', 'utf8');

const replacements = [
  ["'Ссылка скопирована'", "t('PropertyDetails.linkCopied')"],
  ["'Удалить из избранного'", "t('PropertyDetails.removeFromFav')"],
  ["'Добавить в избранное'", "t('PropertyDetails.addToFav')"],
  ["'Поделиться'", "t('PropertyDetails.share')"],
  ["'Убрать из сравнения'", "t('PropertyDetails.removeFromCompare')"],
  ["'Добавить к сравнению'", "t('PropertyDetails.addToCompare')"],
  ["'Открыть галерею'", "t('PropertyDetails.openGallery')"],
  ["'Виртуальный тур'", "t('PropertyDetails.virtualTour')"],
  ["'Смотреть видео'", "t('PropertyDetails.watchVideo')"],
  ["'просмотров'", "t('PropertyDetails.views')"],
  [">м²<", ">{t('PropertyDetails.m2')}<"],
  [">м² /<", ">{t('PropertyDetails.m2')} /<"],
  ["/ м²<", "/ {t('PropertyDetails.m2')}<"],
  [">эт.<", ">{t('PropertyDetails.floor')}<"],
  [">этаж<", ">{t('PropertyDetails.floorFull')}<"],
  [">г.<", ">{t('PropertyDetails.year')}<"],
  [">Класс<", ">{t('PropertyDetails.class')}<"],
  [">Комиссия<", ">{t('PropertyDetails.commission')}<"],
  [">Характеристики<", ">{t('PropertyDetails.characteristics')}<"],
  [">Инфраструктура<", ">{t('PropertyDetails.infrastructure')}<"],
  [">Коммуникации<", ">{t('PropertyDetails.communications')}<"],
  [">Финансы<", ">{t('PropertyDetails.finances')}<"],
  [">Условия аренды<", ">{t('PropertyDetails.rentalTerms')}<"],
  [">Юридическое<", ">{t('PropertyDetails.legal')}<"],
  [">Площадь<", ">{t('PropertyDetails.area')}<"],
  [">Этаж/Этажность здания<", ">{t('PropertyDetails.buildingFloor')}<"],
  [">Год постройки<", ">{t('PropertyDetails.buildYear')}<"],
  [">Состояние<", ">{t('PropertyDetails.condition')}<"],
  [">Планировка<", ">{t('PropertyDetails.layout')}<"],
  [">Вход<", ">{t('PropertyDetails.entrance')}<"],
  [">Парковка<", ">{t('PropertyDetails.parking')}<"],
  [">Лифты<", ">{t('PropertyDetails.elevators')}<"],
  [">Погрузочные доки<", ">{t('PropertyDetails.loadingDocks')}<"],
  [">Новое<", ">{t('PropertyDetails.conditionNew')}<"],
  [">Отличное<", ">{t('PropertyDetails.conditionExcellent')}<"],
  [">Хорошее<", ">{t('PropertyDetails.conditionGood')}<"],
  [">Требует ремонта<", ">{t('PropertyDetails.conditionNeedsRepair')}<"],
  [">Открытая<", ">{t('PropertyDetails.layoutOpen')}<"],
  [">Кабинеты<", ">{t('PropertyDetails.layoutCabinets')}<"],
  [">Смешанная<", ">{t('PropertyDetails.layoutMixed')}<"],
  [">Складская<", ">{t('PropertyDetails.layoutWarehouse')}<"],
  [">Отдельный<", ">{t('PropertyDetails.entranceSeparate')}<"],
  [">Общий<", ">{t('PropertyDetails.entranceCommon')}<"],
  [">С улицы<", ">{t('PropertyDetails.entranceStreet')}<"],
  [">мест<", ">{t('PropertyDetails.places')}<"],
  [">шт<", ">{t('PropertyDetails.pcs')}<"],
  [">Есть<", ">{t('PropertyDetails.has')}<"],
  [">Нет<", ">{t('PropertyDetails.none')}<"],
  [">Пожарная безопасность<", ">{t('PropertyDetails.fireSafety')}<"],
  [">Безопасность<", ">{t('PropertyDetails.security')}<"],
  [">Видеонаблюдение<", ">{t('PropertyDetails.videoSurveillance')}<"],
  [">Охрана<", ">{t('PropertyDetails.guard')}<"],
  [">Контроль доступа<", ">{t('PropertyDetails.accessControl')}<"],
  [">Сигнализация<", ">{t('PropertyDetails.alarm')}<"],
  [">Пожарная сигнализация<", ">{t('PropertyDetails.fireAlarm')}<"],
  [">Электричество<", ">{t('PropertyDetails.electricity')}<"],
  [">Кондиционирование<", ">{t('PropertyDetails.airConditioning')}<"],
  [">Водоснабжение<", ">{t('PropertyDetails.waterSupply')}<"],
  [">Канализация<", ">{t('PropertyDetails.sewerage')}<"],
  [">Газ<", ">{t('PropertyDetails.gas')}<"],
  [">Интернет<", ">{t('PropertyDetails.internet')}<"],
  [">кВт<", ">{t('PropertyDetails.kw')}<"],
  [">Центральное<", ">{t('PropertyDetails.central')}<"],
  [">Сплит-система<", ">{t('PropertyDetails.splitSystem')}<"],
  [">Оптоволокно<", ">{t('PropertyDetails.opticFiber')}<"],
  [">Кабель<", ">{t('PropertyDetails.cable')}<"],
  [">Цена за м²<", ">{t('PropertyDetails.pricePerMeter')}<"],
  [">Депозит<", ">{t('PropertyDetails.deposit')}<"],
  [">Предоплата<", ">{t('PropertyDetails.prepayment')}<"],
  [">Коммунальные платежи<", ">{t('PropertyDetails.communalsIncluded')}<"],
  [">Включены<", ">{t('PropertyDetails.included')}<"],
  [">Отдельно<", ">{t('PropertyDetails.notIncluded')}<"],
  [">Налог<", ">{t('PropertyDetails.tax')}<"],
  [">мес<", ">{t('PropertyDetails.monthShort')}<"],
  [">Кадастровый номер<", ">{t('PropertyDetails.cadastralNumber')}<"],
  [">Тип собственности<", ">{t('PropertyDetails.propertyType')}<"],
  [">Обременения<", ">{t('PropertyDetails.encumbrances')}<"],
  [">Частная собственность<", ">{t('PropertyDetails.privateProperty')}<"],
  [">Описание<", ">{t('PropertyDetails.descTitle')}<"],
  [">Показать полностью<", ">{t('PropertyDetails.showFull')}<"],
  [">Скрыть<", ">{t('PropertyDetails.hide')}<"],
  [">Похожие объекты<", ">{t('PropertyDetails.similarProperties')}<"],
];

for (const rep of replacements) {
  content = content.split(rep[0]).join(rep[1]);
}

fs.writeFileSync('src/app/properties/[id]/page.tsx', content);
console.log('Replaced all property detail items.');
