const fs = require('fs');

let content = fs.readFileSync('src/app/properties/[id]/page.tsx', 'utf8');

const replacements = [
  ['"сум"', "t('PropertyDetails.sum')"],
  ['>Офис<', ">{t('Property.office')}<"],
  ['>Склад<', ">{t('Property.warehouse')}<"],
  ['>Магазин<', ">{t('Property.shop')}<"],
  ['>Кафе/Ресторан<', ">{t('Property.cafeRestaurant')}<"],
  ['>Производство<', ">{t('Property.industrial')}<"],
  ['>Салон<', ">{t('Property.salon')}<"],
  ['>Развлечения<', ">{t('Property.entertainment')}<"],
  ['>Другое<', ">{t('Property.other')}<"],
  ['>Недвижимость<', ">{t('Property.realEstate')}<"],
  ['>Список<', ">{t('Property.list')}<"],
  ["'Загрузка...'", "t('PropertyDetails.loading')"],
  ['title="Поделиться"', "title={t('PropertyDetails.share')}"],
  ['>ТОП<', ">TOP<"],
  ['>Открыть галерею<', ">{t('PropertyDetails.openGallery')}<"],
  ['>360° Виртуальный тур<', ">{t('PropertyDetails.virtualTour360')}<"],
  ['>Смотреть видео<', ">{t('PropertyDetails.watchVideo')}<"],
  ['>просмотров<', ">{t('PropertyDetails.views')}<"],
  ['>м²<', ">{t('PropertyDetails.m2')}<"],
  [' / м²<', " / {t('PropertyDetails.m2')}<"],
  ['} м²', "} {t('PropertyDetails.m2')}"],
  ['} м<', "} {t('PropertyDetails.meter')}<"],
  ['} эт.', "} {t('PropertyDetails.floor')}"],
  ['> этаж<', ">{t('PropertyDetails.floorFull')}<"],
  ['>г.<', ">{t('PropertyDetails.year')}<"],
  ['>Комиссия<', ">{t('PropertyDetails.commission')}<"],
  ["'Характеристики'", "t('PropertyDetails.characteristics')"],
  ["'Инфраструктура'", "t('PropertyDetails.infrastructure')"],
  ["'Коммуникации'", "t('PropertyDetails.communications')"],
  ["'Финансы'", "t('PropertyDetails.finances')"],
  ["'Условия аренды'", "t('PropertyDetails.rentalTerms')"],
  ["'Юридическое'", "t('PropertyDetails.legal')"],
  ['>Этаж<', ">{t('PropertyDetails.floorFull')}<"],
  [' из ${', " {t('PropertyDetails.from')} ${"],
  ['>Класс здания<', ">{t('PropertyDetails.buildingClassLabel')}<"],
  ["'Новое'", "t('PropertyDetails.conditionNew')"],
  ["'Отличное'", "t('PropertyDetails.conditionExcellent')"],
  ["'Хорошее'", "t('PropertyDetails.conditionGood')"],
  ["'Требует ремонта'", "t('PropertyDetails.conditionNeedsRepair')"],
  ["'Открытая'", "t('PropertyDetails.layoutOpen')"],
  ["'Кабинеты'", "t('PropertyDetails.layoutCabinets')"],
  ["'Смешанная'", "t('PropertyDetails.layoutMixed')"],
  ["'Складская'", "t('PropertyDetails.layoutWarehouse')"],
  ["'Отдельный'", "t('PropertyDetails.entranceSeparate')"],
  ["'Общий'", "t('PropertyDetails.entranceCommon')"],
  ["'С улицы'", "t('PropertyDetails.entranceStreet')"],
  ['} мест', "} {t('PropertyDetails.places')}"],
  ["'Есть'", "t('PropertyDetails.has')"],
  ['} шт', "} {t('PropertyDetails.pcs')}"],
  ["'Видеонаблюдение'", "t('PropertyDetails.videoSurveillance')"],
  ["'Охрана'", "t('PropertyDetails.guard')"],
  ["'Контроль доступа'", "t('PropertyDetails.accessControl')"],
  ["'Сигнализация'", "t('PropertyDetails.alarm')"],
  ["'Пожарная сигнализация'", "t('PropertyDetails.fireAlarm')"],
  ["'Центральное'", "t('PropertyDetails.central')"],
  ["'Сплит-система'", "t('PropertyDetails.splitSystem')"],
  ["'Нет'", "t('PropertyDetails.none')"],
  ["'Оптоволокно'", "t('PropertyDetails.opticFiber')"],
  ["'Кабель'", "t('PropertyDetails.cable')"],
  ['} сум', "} {t('PropertyDetails.sum')}"],
  ['> сум<', ">{t('PropertyDetails.sum')}<"],
  [' сум/мес<', " {t('PropertyDetails.sum')}{t('PropertyDetails.perMonth')}<"],
  [' сум/год<', " {t('PropertyDetails.sumPerYear')}<"],
  ['} мес', "} {t('PropertyDetails.monthShort')}"],
  ["'Частная'", "t('PropertyDetails.privateProperty')"],
  ["'Государственная'", "t('PropertyDetails.stateProperty')"],
  ["'Долгосрочная аренда'", "t('PropertyDetails.longTermLease')"],
  ["'Аренда'", "t('PropertyDetails.rent')"],
  ["'Продажа'", "t('PropertyDetails.sale')"],
  ['>Проверено<', ">{t('PropertyDetails.verified')}<"],
  ['>Позвонить<', ">{t('PropertyDetails.callButton')}<"],
  ['>Написать<', ">{t('PropertyDetails.writeButton')}<"]
];

for (const rep of replacements) {
  content = content.split(rep[0]).join(rep[1]);
}

fs.writeFileSync('src/app/properties/[id]/page.tsx', content);
console.log('Replaced');
